### ISSUE TITLE
Please provide requirements list

### ISSUE THREAD

**Issue by jitendracheripally2003** [kivancguckiran/torcs-rl-agent#1]
Hi, can you please provide requirements list for this project and which python version is needed to be installed.

**Comment by kivancguckiran** [comment]
Hey it's been a while since we've worked on this.

We have heavily used this repository: [https://github.com/medipixel/rl_algorithms](https://github.com/medipixel/rl_algorithms)

Maybe you can checkout their codebase from 5 years ago on python version. I simply don't remember.

**Comment by jitendracheripally2003** [comment]
Hi, I have tried their requirements.txt https://github.com/medipixel/rl_algorithms/blob/master/requirements.txt, but it was showing very unresolved errors like torch==1.6.0 is unavailable. If possible, could you please get the list, if it was documented or similar to that?

**Comment by kivancguckiran** [comment]
It seems I was not aware version locking in Python at that time. Unfortunately my laptop which I've run these is stolen long time ago and the environment is lost. This was a joint project and let me see if I can reach out to my colleagues if they have, know or documented the versions somehow.

**Comment by jitendracheripally2003** [comment]
I have tried upgrading the given packages from requirement.txt in medipixel repo, it doesn't show any errors, so I think it works. But can you please tell me if you used torch for the CPU or GPU? I just need to configure that, and it will be done.

**Comment by kivancguckiran** [comment]
Hey you can always use CPU, but the training would be way slower that way. So I suggest you to use GPU.

Cheers that you have worked around the problem.
